### ISSUE TITLE
[PW-7455] Shopware affiliate marketing not working

### ISSUE THREAD

**Issue by andydandy80** [Adyen/adyen-shopware6#295]
**Describe the bug**
The Shopware 6 affiliate marketing is not working with current adyen plugin, nothing is tracked.
The marketing tool ist described here (https://docs.shopware.com/en/shopware-6-en/tutorials-and-faq/affiliateprogram), the codes are attached to shop url and tracked after order in order data record.
When we deactivate adyen plugin and use shopware internal payment methods its working correctly.

**Versions**
Shopware version: 6.4.14.0
Plugin version: 3.6.0

**Comment by andydandy80** [comment]
Any updates here?

**Comment by andydandy80** [comment]
Any updates? Its not working and its necessary and important for our customer!

**Comment by peterojo** [comment]
Fixed in #323

**Comment by andydandy80** [comment]
Sorry, its still not working! I installed the plugin update 3.8.1 and made several tests afterwards. In no case the Affiliate-Code was saved. Whats going wrong?

**Comment by peterojo** [comment]
Hi @andydandy80, we apologize for the error in our release. Unfortunately, we forgot to update the built javascript files. We will include them in the next release, but in the meantime, you can build your storefront javascript files (using `bin/build-storefront.sh`) to get everything working properly. Thank you for your understanding.
